### ISSUE TITLE
Incompatibility with the experimental result in the paper

### ISSUE THREAD

**Issue by Dinxin** [chao1224/n_gram_graph#2] opened 2020-01-02 16:00 UTC
With the code in the 'init' branch, I will get the RMSE on the delaney dataset is '0.9458+/-0.0266', which differs from the result '0.769' in the original paper. I think that maybe it is the hyperparameter configuration that causes this incompatibility. So, what's the exact hyperparameter configuration during the training and testing in the delaney dataset ?

**Comment by chao1224** [comment] 2020-01-03 05:03
Hi @Dinxin 

There could be two possible reasons.
1. As pointed out in #1 (just fixed), the `graph_util.py` is missing. It contains functions for data preprocessing. (which makes me wonder if you are using your own preprocessing functions?)
2. I added the optimal hyper-parameter for `Delaney` in the latest commit. Though it has only been tested on CPU (the GPU server hasn't been back yet), the results match with `Table 13` in the paper.

The optimal hyper-parameters for other tasks will be added.

**Comment by Dinxin** [comment] 2020-01-03 12:08
I am using the 'graph_util.py' from the supplement in the url 'https://papers.nips.cc/paper/9054-n-gram-graph-simple-unsupervised-representation-for-graphs-with-applications-to-molecules'.

**Comment by chao1224** [comment] 2020-01-07 15:57
@Dinxin 
Hi, does this solve your problem? If so, I'll close this issue.
Otherwise, feel free to let me know if you have more questions.

**Closed as completed** 2020-03-27 05:02 UTC

**Comment by kexul** [comment] 2020-05-20 06:11
Hi, I used the hyperparameter in the repo, I cant reproduce the result of delaney either.  my result is 0.84.
